/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE for Visual Studio Code Extension
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include "gpio.h"

/* LED pins on DISC1 board PD12-PD16 */
/* Set GPIO D mode to output and write to output register*/
#define GPIOD_BASE_ADDR 0x40020C00U
#define GPIOA_BASE_ADDR 0x40020000U

#define GPIOx_MODER_OFFSET 0x00U
#define GPIOx_IDR_OFFSET 0x10U
#define GPIOx_ODR_OFFSET 0x14U
#define GPIOx_BSRR_OFFSET 0x18U

#define GPIOD_MODER (*(volatile uint32_t *)(GPIOD_BASE_ADDR + GPIOx_MODER_OFFSET))
#define GPIOD_ODR (*(volatile uint32_t *)(GPIOD_BASE_ADDR + GPIOx_ODR_OFFSET))
#define GPIOD_BSRR (*(volatile uint32_t *)(GPIOD_BASE_ADDR + GPIOx_BSRR_OFFSET))

#define GPIOA_MODER (*(volatile uint32_t *)(GPIOA_BASE_ADDR + GPIOx_MODER_OFFSET))
#define GPIOA_IDR (*(volatile uint32_t *)(GPIOA_BASE_ADDR + GPIOx_IDR_OFFSET))

#define GPIOx_0_Pos 0U
#define GPIOx_12_Pos 12U
#define RESET_STATE 0U



int main(void)
{
    uint32_t GPIO_PIN_ZERO = 0;
    /* LED pins on DISC1 board PD12-PD16 */
    /* Buttons on DISC1 board USR - PA0*/

    /* Enable GPIOA clock */
    configureGpioAClk();

    /* Enable GPIOD clock */
    configureGpioDClk();

    /* Set PD12 as output */
    // /* clear selection of bits you want to write to */
    GPIOD_MODER &= ~((uint32_t)0x3U << (GPIOx_12_Pos * 2U));
    /* write 01 into selection of position*/
    GPIOD_MODER |=  ((uint32_t)0x1U << (GPIOx_12_Pos * 2U));

    /* Set PA0 as input */
    // /* clear selection of bits you want to write to */
    GPIOA_MODER &= ~((uint32_t)0x3U << (GPIOx_0_Pos));

    /* Loop forever */
	while(1)
    {   
        GPIO_PIN_ZERO = GPIOA_IDR & 0x00000001;
        if(GPIO_PIN_ZERO == RESET_STATE)
        {
            /* Turn on LEDs PD12 */
            GPIOD_BSRR |=  ((uint32_t)0x1U << (28U));       // Reset the ODR bit corresponding to pin
            // GPIOD_ODR |= (0U << GPIOx_12_Pos);
        }
        else {

            /* Turn on LEDs PD12 */

            // GPIOD_ODR |= (1U << GPIOx_12_Pos);
            GPIOD_BSRR |=  (0x1U << (GPIOx_12_Pos));        // set the ODR bit corresponding to pin
        
        }

    };

    return 0;
}
