/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE for Visual Studio Code Extension
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include "gpio.h"



int main(void)
{
    RCC->RCC_AHB1ENR |= RCC_GPIODEN;    /* Set*/
    GPIOD->MODER &= ~(3 << (12U*2));   /* Clear bit 24 and 25 of the register*/ 
    GPIOD->MODER |= (1 << (12U*2));     /* set bit 24 of MODER reg: 01 sets to output mode*/
    GPIOD->ODR |= LED12;     /* Turn on LED*/


    /* Loop forever */
	for(;;)
    {
        for(int i=0; i<100000;i++);   /*Simple delay*/
        GPIOD->ODR ^= LED12;     /* Turn on LED, exclusive OR for blinky LED*/
    };
}
