/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE for Visual Studio Code Extension
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include "gpio.h"
#include "uart.h"


/* PA2 TX data out. PA3 RX data In*/

int main(void)
{
    
    uint8_t readGpioPinZero = 0;
    /* LED pins on DISC1 board PD12-PD16 */
    uint8_t gpioPin2 = 2U;
    uint8_t gpioPin3 = 3U;

    /* Buttons on DISC1 board USR - PA0*/

    /* Enable GPIOA clock */
    configureGpioAClk();
    /*GPIOx_AFRL set to 0111: AF7 -> UART */

    /* Set PA2 as alternate function*/
    setGpioMode(GPIOA, gpioPin2, ALT_FUNC);

    /* Set PA3 as alt_func */
    setGpioMode(GPIOA, gpioPin3, ALT_FUNC);

    /*Init UART configuration*/

    /*Configure PA2 and PA3 as UART TX and RX pins*/

    /* Loop forever */
	while(1)
    {   
        /* Read status of GPIOA pin Zero*/
        readGpioPinZero = getGpioPinData(GPIOA, gpioPin0);
        if(readGpioPinZero == RESET)
        {
            /* Turn off LEDs PD12 */
            gpioOutputSetReset(GPIOD, gpioPin12, RESET);
        }
        else {
            /* Turn on LEDs PD12 */
            gpioOutputSetReset(GPIOD, gpioPin12, SET);      
        }
    };

    return 0;
}
