/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE for Visual Studio Code Extension
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <stdio.h>
#include "gpio.h"
#include "uart.h"


/* PA2 TX data out. PA3 RX data In*/

int main(void)
{
    uint8_t gpioPin2 = 2U;
    uint8_t gpioPin3 = 3U;
    uint8_t uartAltFun = 7U;

    /* Buttons on DISC1 board USR - PA0*/

    /* Enable GPIOA clock */
    configureGpioAClk();

    /*Init UART configuration*/
    configureUart2Clk();


    /* Set PA2 as alternate function*/
    setGpioMode(GPIOA, gpioPin2, ALT_FUNC);

    /* Set PA3 as alt_func */
    setGpioMode(GPIOA, gpioPin3, ALT_FUNC);

    /*Set 01: Pull-up on the register*/
    gpioConfigPupdr(GPIOA, gpioPin3);

    /*Set GPIO alt function to UART*/
    /*GPIOx_AFRL set to 0111: AF7 -> UART */
    setGpioAltFun(GPIOA, gpioPin2, uartAltFun);
    setGpioAltFun(GPIOA, gpioPin3, uartAltFun);

    /*Set GPIO PUPD register to avoid floating inputs*/



    /*Set baud rate for UART*/
    configureUart2BaudRate();

    /*Configure UART TX,RX UE pins*/
    configureUart2Register();

    /* Loop forever */
	while(1)
    {   
        uint32_t tempVar;
        tempVar = uart2RxData();
        printf("Value read from terminal: %d\n", tempVar);

    };

    return 0;
}
